apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: energi_node
  labels:
    app: energi
spec:
  serviceName: "energi"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: energi
  template:
    metadata:
      labels:
        app: energi
    spec:
      containers:
      - name: energi
        image: sayaligbe/energi_node:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 39797
          name: p2p
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: energi_data
          mountPath: /home/energiuser/.energicore3
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        livenessProbe:
          tcpSocket:
            port: 39797
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 39797
          initialDelaySeconds: 10
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: energi_data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 150Gi
      storageClassName: gp2
